import {
  Activity,
  AlarmClock,
  Apple,
  Armchair,
  ArrowLeftRight,
  ArrowRightLeft,
  BadgeDollarSign,
  BadgePercent,
  Baby,
  Banknote,
  BarChart3,
  Beer,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Cake,
  CalendarDays,
  CalendarHeart,
  Calculator,
  Car,
  CarFront,
  ChartLine,
  Church,
  CigaretteOff,
  CircuitBoard,
  ClipboardList,
  Clock,
  Coins,
  CreditCard,
  Divide,
  Droplets,
  Dumbbell,
  Egg,
  Flag,
  Flame,
  Flower2,
  Fuel,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  Hourglass,
  Home,
  House,
  KeyRound,
  Landmark,
  LayoutGrid,
  LineChart,
  Orbit,
  Palmtree,
  Percent,
  PiggyBank,
  Plane,
  Plug,
  Receipt,
  Repeat,
  Ruler,
  Scale,
  ScrollText,
  ShieldCheck,
  Sigma,
  SolarPanel,
  Split,
  Square,
  Stethoscope,
  Sun,
  Tag,
  Target,
  Thermometer,
  TrendingDown,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";export interface CategoryVisual {
  icon: LucideIcon;
  color: string;
}

const categoryVisuals: Record<string, CategoryVisual> = {
  "Økonomi": { icon: Wallet, color: "text-blue-600 dark:text-blue-400" },
  "Ekonomi": { icon: Wallet, color: "text-blue-600 dark:text-blue-400" },
  "Bolig": { icon: House, color: "text-emerald-600 dark:text-emerald-400" },
  "Bostad": { icon: House, color: "text-emerald-600 dark:text-emerald-400" },
  "Lån": { icon: Landmark, color: "text-amber-600 dark:text-amber-400" },
  "Lån & Rente": { icon: Landmark, color: "text-amber-600 dark:text-amber-400" },
  "Lån & Ränta": { icon: Landmark, color: "text-amber-600 dark:text-amber-400" },
  "Sundhed": { icon: HeartPulse, color: "text-rose-600 dark:text-rose-400" },
  "Helse": { icon: HeartPulse, color: "text-rose-600 dark:text-rose-400" },
  "Hälsa": { icon: HeartPulse, color: "text-rose-600 dark:text-rose-400" },
  "Familie": { icon: Users, color: "text-pink-600 dark:text-pink-400" },
  "Familj": { icon: Users, color: "text-pink-600 dark:text-pink-400" },
  "Familie & Sundhed": { icon: Users, color: "text-pink-600 dark:text-pink-400" },
  "Familie & Helse": { icon: HeartPulse, color: "text-rose-600 dark:text-rose-400" },
  "Familj & Hälsa": { icon: HeartPulse, color: "text-rose-600 dark:text-rose-400" },
  "Uddannelse": { icon: GraduationCap, color: "text-indigo-600 dark:text-indigo-400" },
  "Erhverv": { icon: Briefcase, color: "text-cyan-600 dark:text-cyan-400" },
  "Hverdag": { icon: Sun, color: "text-orange-600 dark:text-orange-400" },
  "Vardag": { icon: Sun, color: "text-orange-600 dark:text-orange-400" },
  "Verktøy": { icon: Sun, color: "text-orange-600 dark:text-orange-400" },
  "Verktyg": { icon: Sun, color: "text-orange-600 dark:text-orange-400" },
  "Praktisk": { icon: Wrench, color: "text-teal-600 dark:text-teal-400" },
  "Praktiskt": { icon: Wrench, color: "text-teal-600 dark:text-teal-400" },
  "Matematik": { icon: Percent, color: "text-violet-600 dark:text-violet-400" },
  "Matematikk": { icon: Percent, color: "text-violet-600 dark:text-violet-400" },
};

const fallbackCategoryVisual: CategoryVisual = {
  icon: LayoutGrid,
  color: "text-gray-600 dark:text-gray-400",
};

export function getCategoryVisual(category: string): CategoryVisual {
  return categoryVisuals[category] ?? fallbackCategoryVisual;
}

const calculatorIcons: Record<string, LucideIcon> = {
  "/1rm": Dumbbell,
  "/aegloesning": Flower2,
  "/afkast": ChartLine,
  "/aktieskat": Coins,
  "/alder": Cake,
  "/andelsbolig": Building,
  "/arveafgift": ScrollText,
  "/barselsdagpenge": Baby,
  "/bil": Car,
  "/billaan": CarFront,
  "/bmi": Scale,
  "/boernepenge": HandCoins,
  "/bolan": House,
  "/boliglaan": House,
  "/boligstoette": Building2,
  "/braendstof": Fuel,
  "/brok": Divide,
  "/brutto-netto": Split,
  "/bryllup": Heart,
  "/budget": Wallet,
  "/dagpenge": ClipboardList,
  "/dato": CalendarDays,
  "/del-regning": Utensils,
  "/efterloen": Armchair,
  "/ejendomsvaerdiskat": Home,
  "/elberegner": Zap,
  "/elbil": Plug,
  "/enheder": Ruler,
  "/enhedspris": Tag,
  "/fart": Gauge,
  "/feriepenge": Palmtree,
  "/forbrugslaan": CreditCard,
  "/gaeldsfri": Flag,
  "/gennemsnit": Sigma,
  "/husleje": KeyRound,
  "/kalorier": Apple,
  "/konfirmation": Church,
  "/kropsfedt": Activity,
  "/kvadratmeter": Square,
  "/laaneberegner": Landmark,
  "/leasing": Repeat,
  "/loen-efter-skat": Banknote,
  "/lon-efter-skatt": Banknote,
  "/loen-konverter": ArrowRightLeft,
  "/loenstigning": TrendingUp,
  "/moms": Receipt,
  "/motion-kalorier": Flame,
  "/nedtaelling": AlarmClock,
  "/ohm": CircuitBoard,
  "/opsparing": PiggyBank,
  "/pension": Hourglass,
  "/planetvaegt": Orbit,
  "/rabat": Tag,
  "/procent": Percent,
  "/promille": Beer,
  "/rejsebudget": Plane,
  "/renteberegner": LineChart,
  "/rentefradrag": Landmark,
  "/skattefradrag": BadgePercent,
  "/solceller": SolarPanel,
  "/sparemaal": Target,
  "/studielaan": BookOpen,
  "/su": GraduationCap,
  "/sygedagpenge": Stethoscope,
  "/temperatur": Thermometer,
  "/termin": CalendarHeart,
  "/tidsberegner": Clock,
  "/tidszone": Globe,
  "/timepris": BadgeDollarSign,
  "/topskat": BarChart3,
  "/vaegttab": TrendingDown,
  "/valuta": ArrowLeftRight,
  "/vandbehov": Droplets,
  "/proteinbehov": Egg,
  "/befordringsfradrag": Car,
  "/rygestop": CigaretteOff,
};

export function getCalculatorIcon(href: string): LucideIcon {
  return calculatorIcons[href] ?? Calculator;
}
