import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { OrganizationSchema, WebSiteSchema } from "@/components/StructuredData";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CookieConsent from "@/components/CookieConsent";
import { ThemeProvider } from "@/components/ThemeProvider";
import { LocaleProvider } from "@/components/LocaleProvider";
import { SkipLink } from "@/components/SkipLink";
import ServiceWorkerRegistration from "@/components/ServiceWorkerRegistration";
import BeregnerAssistent from "@/components/BeregnerAssistent";
import { getLocale, getCurrentDomainConfig } from "@/lib/get-locale";
import { getTranslations } from "@/lib/i18n";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export async function generateMetadata(): Promise<Metadata> {
  const domainConfig = await getCurrentDomainConfig();
  const t = getTranslations(domainConfig.locale);
  const baseUrl = domainConfig.baseUrl;

  return {
    metadataBase: new URL(baseUrl),
    title: {
      default: `${domainConfig.siteName} - ${t.site.tagline}`,
      template: `%s | ${domainConfig.siteName}`,
    },
    description: t.site.description,
    authors: [{ name: domainConfig.siteName }],
    creator: domainConfig.siteName,
    publisher: domainConfig.siteName,
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
    openGraph: {
      type: "website",
      locale: domainConfig.ogLocale,
      url: baseUrl,
      siteName: domainConfig.siteName,
      title: `${domainConfig.siteName} - ${t.site.tagline}`,
      description: t.site.description,
      // OG image is generated by src/app/opengraph-image.tsx (file convention).
    },
    twitter: {
      card: "summary_large_image",
      title: `${domainConfig.siteName} - ${t.site.tagline}`,
      description: t.site.description,
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: baseUrl,
    },
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#2563eb",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const domainConfig = await getCurrentDomainConfig();
  const htmlLang = domainConfig.hreflangCode;
  return (
    <html lang={htmlLang}>
      <head>
        {/* Plausible Analytics - Self-hosted */}
        <script
          defer
          data-domain={domainConfig.analyticsDataDomain}
          src="https://analytics.holstjensen.eu/js/script.js"
        />

        {/* Google AdSense */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1902871361369866"
          crossOrigin="anonymous"
        />

        <OrganizationSchema
          name={domainConfig.siteName}
          url={domainConfig.baseUrl}
          description={getTranslations(locale).site.description}
        />
        <WebSiteSchema
          name={domainConfig.siteName}
          url={domainConfig.baseUrl}
          description={getTranslations(locale).site.description}
        />
      </head>
      <body
        className={`${inter.variable} font-sans min-h-screen bg-gray-50 dark:bg-gray-950 flex flex-col antialiased transition-colors`}
      >
        <ThemeProvider>
          <LocaleProvider locale={locale} domainConfig={domainConfig}>
            <SkipLink />
            <Header />

            <main
              id="main-content"
              tabIndex={-1}
              className="flex-1 max-w-6xl mx-auto px-4 py-8 w-full outline-none"
            >
              {children}
            </main>

            <CookieConsent />
            <ServiceWorkerRegistration />
            <BeregnerAssistent />
          </LocaleProvider>
        </ThemeProvider>

        <Footer />
      </body>
    </html>
  );
}
